language: generic
dist: xenial
addons:
  apt:
    sources:
    - sourceline: ppa:opencpu/imagemagick
    packages:
    - libmagick++-dev
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR/src/
script:
- texliveonfly main.tex
- latexmk -pdf main.tex
deploy:
  - provider: releases
    file: 
      - "./main.pdf"
    on:
      tags: true
    edge: true
  - provider: pages
    skip_cleanup: true
    keep_history: true
    target_branch: gh-pages
    on:
      branch: main